- name: Print environment
  debug:
    msg: "This server belongs to {{ env }}"

- name: Install nginx
  ansible.builtin.dnf:
    name: "{{ package_name }}"
    state: present

- name: Deploy template
  ansible.builtin.template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
  notify: restart nginx
  
- name: Start nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes